name: Build documentation

on:
  push:
    branches:
      # This should match the DOC3_BRANCH value in the psycopg-website Makefile
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs build
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: psycopg/psycopg-website
          event-type: psycopg3-commit
          token: ${{ secrets.ACCESS_TOKEN }}
