name: Lint

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "**"
  # Note: trying to exclude pull requests because it results in duplicate job
  # on the commits belonging to pull requests.
  # pull_request:
  schedule:
    - cron: '18 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    if: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: install packages to tests
        run: pip install ./psycopg[dev,test]

      - name: Lint codebase
        run: pre-commit run -a --color=always

      - name: Check for sync/async inconsistencies
        run: ./tools/async_to_sync.py --check --all

      - name: Install requirements to generate docs
        run: sudo apt-get install -y libgeos-dev

      - name: Install Python packages to generate docs
        run: pip install ./psycopg[docs] ./psycopg_pool

      - name: Check documentation
        run: sphinx-build -W -T -b html docs docs/_build/html
